# Generated by Django 3.0.6 on 2020-06-05 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Turma')),
                ('section', models.CharField(max_length=100, verbose_name='Séries')),
                ('state', models.CharField(max_length=30, verbose_name='Situação')),
                ('link', models.CharField(max_length=100, verbose_name='Link')),
                ('teachers_email', models.CharField(max_length=100, verbose_name='Email professores')),
                ('course_email', models.CharField(max_length=100, verbose_name='Email turma')),
                ('created_at', models.DateTimeField(verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(verbose_name='Última atualização')),
                ('mnemonic', models.CharField(blank=True, max_length=4, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['mnemonic', 'name'],
                'unique_together': {('id', 'teacher')},
            },
        ),
    ]
